# Generated by Django 6.0.4 on 2026-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='media/')),
                ('texto', models.TextField(max_length=500)),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
