# Generated by Django 6.0.4 on 2026-07-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('prazo', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
